// Start python app.py and build the frontend before this local browser smoke test.
import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {visibleGraph,layout} from '../src/graph.js';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:8000');
 const analysisResponse=page.waitForResponse(r=>r.url().endsWith('/api/analyze'));
 await page.getByRole('button',{name:'Run analysis'}).click();
 const data=await (await analysisResponse).json();
 await page.locator('.rank').first().waitFor({timeout:30000});
 const gid=await page.locator('.rank code').first().textContent();
 await page.getByRole('textbox',{name:'Search exact gid'}).fill(gid);
 await page.getByRole('button',{name:'Find',exact:true}).click();
 await page.locator('.evidence code').waitFor();
 assert.equal(await page.locator('.evidence code').textContent(),gid);
 assert.match(await page.locator('.graph-meta').textContent(),/Selected neighborhood/);
 await page.getByRole('button',{name:'Zoom in'}).click();
 await page.getByRole('button',{name:'Fit view'}).click();
 const canvas=await page.locator('canvas').boundingBox();
 const graph=visibleGraph(data,gid,'neighborhood','all'),positions=layout(graph.nodes);
 const xs=[...positions.values()].map(p=>p.x),ys=[...positions.values()].map(p=>p.y);
 const minX=Math.min(...xs)-40,maxX=Math.max(...xs)+40,minY=Math.min(...ys)-40,maxY=Math.max(...ys)+40;
 const k=Math.min(2.5,(canvas.width-70)/(maxX-minX),(canvas.height-100)/(maxY-minY));
 const points=graph.nodes.map(n=>({n,x:canvas.width/2+(positions.get(n.gid).x-(minX+maxX)/2)*k,y:canvas.height/2+(positions.get(n.gid).y-(minY+maxY)/2)*k}));
 const target=points.find(p=>p.n.gid!==gid&&p.x>20&&p.x<canvas.width-320&&p.y>90&&p.y<canvas.height-70);
 assert.ok(target,'Visible hover target');
 await page.mouse.move(canvas.x+target.x,canvas.y+target.y);
 await page.waitForFunction(id=>document.querySelector('.evidence code')?.textContent===id,target.n.gid);
 await page.mouse.click(canvas.x+target.x,canvas.y+target.y);
 await page.mouse.move(canvas.x+20,canvas.y+150);
 assert.equal(await page.locator('.evidence code').textContent(),target.n.gid);
 await page.mouse.move(canvas.x+canvas.width/2,canvas.y+canvas.height/2);
 await page.mouse.wheel(0,-200);
 await page.mouse.move(canvas.x+40,canvas.y+180);
 await page.mouse.down();
 await page.mouse.move(canvas.x+95,canvas.y+200,{steps:5});
 await page.mouse.up();
 await page.getByRole('button',{name:'Fit view'}).click();
 await page.getByRole('combobox',{name:'Color by'}).selectOption('cluster');
 await page.getByRole('combobox',{name:'Cluster',exact:true}).selectOption(String(data.clusters.at(-1).cluster_id));
 assert.match(await page.locator('.graph-meta').textContent(),/Full network/);
 await page.getByRole('button',{name:'Full network',exact:true}).click();
 await page.getByRole('textbox',{name:'Search exact gid'}).fill('does-not-exist');
 await page.getByRole('button',{name:'Find',exact:true}).click();
 assert.equal(await page.getByRole('alert').textContent(),'Account not found');
 await page.getByRole('textbox',{name:'Search exact gid'}).fill(gid);
 await page.getByRole('button',{name:'Find',exact:true}).click();
 await page.getByRole('combobox',{name:'Language'}).selectOption('ru');
 assert.equal(await page.locator('html').getAttribute('lang'),'ru');
 assert.equal(await page.locator('h1').textContent(),'Граф переводов');
 const response=await page.request.get('http://127.0.0.1:8000/api/exports/nodes_roles.csv');
 assert.equal(response.status(),200);
 await page.screenshot({path:'dist/review-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.locator('canvas').isVisible());
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.deepEqual(errors,[]);
 console.log('Browser passed: load, analysis, exact-ID search, zoom, cluster colors, Russian, downloads, mobile viewport; no page errors.');
}finally{await browser.close();}
