import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {visibleGraph,layout} from '../src/graph.js';
const base=process.env.AML_TEST_URL||'http://127.0.0.1:8000';
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1500,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(base);
 const pending=page.waitForResponse(r=>r.url().endsWith('/api/analyze'));
 await page.getByRole('button',{name:'Run analysis'}).click();
 const data=await(await pending).json();
 const seeds=data.nodes.filter(n=>n.is_seed);
 const picker=page.getByRole('combobox',{name:'Observe seed account'});
 await expect(picker.locator('option')).toHaveCount(seeds.length+1);
 const isolated=seeds.find(n=>n.counterparty_count===0);
 await picker.selectOption(isolated.gid);
 await expect(page.locator('.evidence code')).toHaveText(isolated.gid);
 await expect(page.locator('.no-edges')).toBeVisible();
 await expect(page.locator('.evidence h3')).toHaveText('Peripheral');
 const seed=seeds.find(n=>n.out_degree>=3&&n.out_degree<12);
 assert.ok(seed);
 await picker.selectOption(seed.gid);
 await page.waitForTimeout(600); // Verify settled animated layout, not reduced-motion mode.
 const box=await page.locator('canvas').boundingBox();
 const graph=visibleGraph(data,seed.gid,'neighborhood','all'),positions=layout(graph.nodes,seed.gid);
 const ps=[...positions.values()],xs=ps.map(p=>p.x),ys=ps.map(p=>p.y);
 const minX=Math.min(...xs)-40,maxX=Math.max(...xs)+40,minY=Math.min(...ys)-40,maxY=Math.max(...ys)+40;
 const k=Math.min(2.5,(box.width-70)/(maxX-minX),(box.height-100)/(maxY-minY));
 const target=graph.nodes.map(n=>({n,x:box.width/2+(positions.get(n.gid).x-(minX+maxX)/2)*k,y:box.height/2+(positions.get(n.gid).y-(minY+maxY)/2)*k})).find(p=>p.n.gid!==seed.gid&&p.x>80&&p.x<box.width-320&&p.y>160&&p.y<box.height-100);
 assert.ok(target);
 await page.mouse.click(box.x+target.x,box.y+target.y);
 await expect(page.locator('.previous-marker')).toBeVisible();
 await expect(page.locator('.previous-marker')).toHaveAttribute('aria-label',`Previous account: ${seed.gid}`);
 await expect(page.locator('.origin')).toContainText(seed.gid);
 await expect(page.locator('.edge-legend')).toContainText('Incoming');
 await expect(page.locator('.edge-legend')).toContainText('Outgoing');
 await page.waitForTimeout(500);
 await page.screenshot({path:'dist/seed-navigation.png'});
 await page.locator('.previous-marker').click();
 await expect(page.locator('.evidence code')).toHaveText(seed.gid);
 await expect(page.locator('.previous-marker')).toHaveCount(0);
 await page.getByLabel('Hops',{exact:true}).selectOption('4');
 await page.getByLabel('Trace direction',{exact:true}).selectOption('out');
 await page.getByText('What does priority mean?',{exact:true}).click();
 await expect(page.locator('.help').first()).toContainText('not a probability');
 await page.getByText('Data coverage and limitations',{exact:true}).click();
 await expect(page.locator('.coverage')).toContainText('Isolated seeds: 19');
 await page.getByRole('combobox',{name:'Language'}).selectOption('ru');
 await expect(page.getByRole('combobox',{name:'Просмотр seed-счёта'})).toHaveValue(seed.gid);
 assert.deepEqual(errors,[]);
 console.log('Passed: all seeds including isolates, animated navigation, prior-node back badge, origin, incoming/outgoing legend, 4-hop outgoing trace, priority help, coverage, Russian.');
}finally{await browser.close();}
